parameters:
#    core.example.class: kblog\frontend\CoreBundle\Example

services:
#    core.example:
#        class: %core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
