<?php

namespace kblog\CoreBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlogImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogImagesRepository extends EntityRepository
{
}
