services:
    sonata.admin.post:
        class: kblog\CoreBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Categories" }
        arguments:
            - ~
            - kblog\CoreBundle\Entity\Category
            - ~
        calls:
            - [ setTranslationDomain, [CoreBundle]]
